kind: Secret
apiVersion: v1
metadata:
  name: demo-secret-helm-values
  namespace: avp-demo
  annotations:
    avp.kubernetes.io/path: "secret/data/demo"
type: Opaque
stringData:
  demo-secret: {{ .Values.secretkey | quote }}